# Generated by Django 6.1.1 on 2026-10-03 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueno_nombre', models.CharField(max_length=100)),
                ('dueno_telefono', models.CharField(max_length=20)),
                ('mascota_nombre', models.CharField(max_length=100)),
                ('mascota_tipo', models.CharField(max_length=50)),
                ('mascota_raza', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='confirmada', max_length=50)),
            ],
            options={
                'db_table': 'petcare_reserva',
            },
        ),
        migrations.CreateModel(
            name='ServicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'petcare_servicio',
            },
        ),
        migrations.DeleteModel(
            name='ClienteModel',
        ),
        migrations.AddField(
            model_name='reservamodel',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.serviciomodel'),
        ),
    ]
